<a href="https://colab.research.google.com/github/RajeevRanjany/Ml/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Advantages of Numpy Arrays :
1. Allow several Matematical Operations
2. Faster oeprations


In [4]:
import numpy as np

List Vs Numpy - Time Taken

In [1]:
from time import process_time


Time taken by a list


In [10]:
python_list = [i for i in range(10000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)
#

0.6796174869999998


In [11]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)
#

0.008563346999999943


In [13]:
print(0.6796174869999998 > 0.008563346999999943)

True


Numpy Arrays


In [18]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [19]:
#np arrray
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
#

[1 2 3 4 5]


numpy.ndarray

In [22]:
#Creating 1d array
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [24]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [26]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Intial placeholders in numpy arrays


In [28]:
# create numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
# create numpy array of one
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# create numpy array of specific value
z = np.full((4,5),11)
print(z)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


In [36]:
# create numpy array of identity matrix
a = np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
# create numpy array of random value
b = np.random.random((3,3))
print(b)

[[0.10216989 0.16763461 0.20028091]
 [0.23235742 0.60999947 0.7784527 ]
 [0.08033553 0.38633923 0.61897496]]


In [47]:
# create numpy array of random value in sprcific ranges
c = np.random.randint(100,200, (3,3))
print(c)

[[194 164 143]
 [152 108 143]
 [151 143 138]]


In [50]:
#array of evenly spaced value --> specifying number of values requiered
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [56]:
#array of evenly spaced valued --> specify the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [58]:
#conver a list to a numpy array
list2 = [10,12,23,43,34,23,23]
np_array = np.asarray(list2)
print(np_array)

[10 12 23 43 34 23 23]


analysing a numpy array


In [65]:
c = np.random.randint(10,90,(9,5))
print(c)


[[21 73 54 17 47]
 [36 77 81 85 31]
 [45 22 21 13 27]
 [49 59 63 82 22]
 [51 30 47 27 62]
 [83 46 39 42 60]
 [76 34 37 55 12]
 [37 69 44 78 82]
 [15 45 36 72 87]]


In [66]:
print(c.shape)

(9, 5)


In [69]:
#check dimensiosn -> row and column
print(c.ndim)

2



In [72]:
print(c.size)

45


In [73]:
print(c.dtype)

int64


Mathematical operations on np array

In [76]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5]


In [80]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 5 5]
 [9 1 2]
 [1 9 5]]
[[14 16 11]
 [16 10 19]
 [15 15 17]]
[[15 21 16]
 [25 11 21]
 [16 24 22]]
[[-13 -11  -6]
 [ -7  -9 -17]
 [-14  -6 -12]]
[[ 14  80  55]
 [144  10  38]
 [ 15 135  85]]
[[0.07142857 0.3125     0.45454545]
 [0.5625     0.1        0.10526316]
 [0.06666667 0.6        0.29411765]]


In [81]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 21 16]
 [25 11 21]
 [16 24 22]]
[[-13 -11  -6]
 [ -7  -9 -17]
 [-14  -6 -12]]
[[ 14  80  55]
 [144  10  38]
 [ 15 135  85]]
[[0.07142857 0.3125     0.45454545]
 [0.5625     0.1        0.10526316]
 [0.06666667 0.6        0.29411765]]


Array Manupulations

In [82]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 3 5]
 [7 2 0]]
(2, 3)


In [83]:
#transpose
tran = np.transpose(array)
print(tran)

[[9 7]
 [3 2]
 [5 0]]


In [84]:
tran2 = array.T
print(tran2)

[[9 7]
 [3 2]
 [5 0]]


In [85]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[1 6 8]
 [4 3 3]]
(2, 3)


In [86]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 6]
 [8 4]
 [3 3]]
(3, 2)
